services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - BackEnd
    volumes:
      - postgres_data:/var/lib/postgresql/MAJOR/docker
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      pgadmin_listen_port: 5050
    ports:
      - "5050:5050"
    networks:
      - BackEnd
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_mg
    environment:
      RABBITMQ_DEFAULT_USER: TheGrayDane
      RABBITMQ_DEFAULT_PASS: '!2HoppeBolde'
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - BackEnd
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
volumes:
  postgres_data: {}
  rabbitmq_data: {}
  rabbitmq_logs: {}
  pgadmin_data: {}
networks:
  BackEnd:
    #driver: bridge
    #ipam:
    #  config:
    #    - subnet: 196.18.0.0/16
    #      gateway: 196.18.0.1